### PR TITLE
Shape up

### PR DESCRIPTION
**Pull request by s-weigand**
Hey there,
I have a project, were I want to export config files in a password protected zip and stumbeled across your project, so thanks for all the work :smiley:

Sadly the code doesn't work on Windows out of the box since [pycrypto](https://github.com/dlitz/pycrypto/issues/254) is deprecated and also needs compiling. But luckily there is [pycryptodome](https://github.com/Legrandin/pycryptodome) a fork of `pycrypto` , which is still maintained, distributed as wheels via PyPi and cross platform. With a few import changes I got your code running on Windows, by just pip installing it.

What did in this PR:
- changed `Crypto` imports to `Cryptodome`, with `pycryptodomex` there shouldn't be conflicts with installations of the original `pycrypto` 
- changed test runner in `tox.ini` to `pytest`, since it provies a better overview than plain unittest (I kept it so only the testfiles which were run by testrunner are run)
- added CI tests for Linux, OsX and Windows (travis + appveyor)
- made the code pep8 conform (passes flake8 now)
- added some badges to the readme so it looks nice
- removed tests for py34 and py35, since f-strings in `test/support/__init__.py` made them fail, if you want to support them I can cange the code there and add them back to the test suite
- added code coverage output and upload to coveralls.io
- added rudimentary docs, that will work with `readthedocs`

To use [travis](https://travis-ci.org/), [appveyor](https://ci.appveyor.com/), [readthedocs](https://readthedocs.org/) and [coveralls.io](https://coveralls.io), you need to login with your github account and activate the repo.

### CODE REVIEW

**Comment by s-weigand** [comment]
Sorry for the huge PR, if you want I can try to `cherry-pick` it and make it into multipe more bite sized PR's.
Just got excited and wanted to implement it in my project asap 😄

**Comment by danifus** [comment]
Hi, thanks for the changes, particularly the pycrypto stuff. I didn't realise that project had been abandoned.

I'm happy to accept all the changes but was planning on delaying the pep8 changes. As zipfile.py is a modified version of zipfile.py found in Python, I have a plan (haven't started the process yet) to see if there is any interest in pulling the zipfile changes back into Python itself and wanted to keep the diff to only the places that had functional changes. Not sure if that will help them review but thought it might be useful. There are a lot of changes in between this pyzipper's zipfile.py and Python's, so it might be a hard sell to get it merged. After that I would like to pep8 that file :)

**Comment by s-weigand** [comment]
Sounds really nice 😄 
Maybe you could make an extra branch like `python-upstream` for that purpose and when they accept it remove the `zipfile.py` from this package and just use the std lib one (guess to prevent problems that won't happen before py38).
I got no idea how the python core team operates, but i guess they want it all self contained, so `zipfile_aes.py`, which relies on 3rd party code, will be out of the picture anyway .... just an idea.

P.S.: I got the hint that `pycrypto` is dead and `pycryptodome` is the way to go from a comment in an issue in `pycrypto`. There are many recent PR's and issues on `pycrypto`, but last changes were 3y ago, the owner is still active at GH tho ... guess i will drop him a mail, to redirect people on the readme to `pycryptodome` since `pycrypto` was reported to have security issues on stackoverflow

**Comment by danifus** [comment]
That's a good idea. I've made a separate branch for the minimal pep8 changes so I'm happy to merge this code.

Would it be possible for you to re-add test support for some of the older python 3 versions? I'd like to support them if possible.

After that I'll ship a new version to pypi.

Thanks for you work!

**Comment by s-weigand** [comment]
I made a separat PR #3 for python 3.5, since it requires a lot of version checks to handle path objects.

**Comment by s-weigand** [comment]
- made changes to use pyup

[pyup](https://pyup.io/) is a service that send automated PR's if there is an update for a dependency, so it's easy to see if there are breaking changes

**Pull request merged**
